# SPDX-License-Identifier: GPL-3.0-or-later
# Replaces /usr/lib/modprobe.d/nvidia-utils.conf, which disables nouveau for every NVIDIA GPU.
# On OwneetOS owneet-gpu-select chooses between nvidia-open and nouveau at boot
# (/run/modprobe.d/owneet-gpu.conf), so GPUs older than Turing keep a working driver.
