# SPDX-License-Identifier: GPL-3.0-or-later
# NVIDIA's driver answers DDC/CI (monitor brightness, Settings → Display) only with its software
# I2C; the setting recommended by ddcutil (its nvidia-i2c.conf).
options nvidia NVreg_RegistryDwords="RMUseSwI2c=0x01;RMI2cSpeed=100"
