# SPDX-License-Identifier: GPL-3.0-or-later
# The Xbox wireless dongle is also claimed by mt76x2u, the driver of some USB Wi-Fi adapters.
# Load xone_dongle first so it gets the dongle, while mt76x2u keeps serving real Wi-Fi adapters.
# (Upstream xone blacklists mt76x2u and xpad instead; OwneetOS does not, so those Wi-Fi adapters
# and the many wired controllers handled by xpad keep working.)
softdep mt76x2u pre: xone_dongle
